### ISSUE TITLE
How to set or find out DevEUI?

### ISSUE THREAD

**Issue by FursinMihail** [joba-1/STM32L0TTN#2]
In the code I see only NwkSkey AppSkey and DevAddr. What should I do with DevEUI? I'm trying to transfer data to TTN.
Thank you in advance!

**Comment by joba-1** [comment]
it is not needed for the ABP activation mode, only for devices using OTAA.

**Comment by FursinMihail** [comment]
Yes it works thanks! There was a problem with the radio frequency and not the TTN configuration.

**Comment by joba-1** [comment]
you‘re welcome. Thanks for reporting back.
May I ask if you actually used my code? Did you use it for the „new“ V3 TTN? I thought it might not work…

**Comment by FursinMihail** [comment]
Yes, works with V3 TTN. 
![image](https://user-images.githubusercontent.com/56782781/141958946-b6b402a9-ff6b-4fa6-a0f7-31a51a15e234.png)

And the application server.
![image](https://user-images.githubusercontent.com/56782781/141959216-23f7407c-1ef5-43ac-ab00-5ee4320cadcd.png)

Can you tell me if I understand correctly that there is no mechanism for confirming the receipt of a message?

**Comment by joba-1** [comment]
> Yes, works with V3 TTN.

Great news - I was afraid I have to dump my devices when they shut down V2 in 2 weeks.

> Can you tell me if I understand correctly that there is no mechanism for confirming the receipt of a message?

LoraWAN has this mechanism (downlinks) but my code has not.

I sacrificed it for space and power usage. An ATTiny84 and even more an STM32L011 has really low power usage. My devices run several months (ATTiny84) to well over a year and counting (STM32L011) without needing my attention. If you have to put the RFW95 in receiving mode for a while after each uplink that drains the power quite a bit. And for what? To adjust power levels and frequencies, requirements that pretty much never change (in my usecase). And so far I was not able to squeeze the code for that so that it fits in the 16kB that are available.

**Comment by FursinMihail** [comment]
Got it, thanks. You can refuse hal and ll and there will be a lot of free space :) I don't like these libraries.

**Comment by joba-1** [comment]
I agree regarding the HugeArmLib :D, but I wasnt really able to do without LL (ST docs and examples all use it, if not HAL) and it seems to be quite lean.

Reading chip reference manuals and understand all quirks necessary when using CMSIS so far was too much hassle for me as a ST/Arm beginner. Maybe you have some docs/resources that could make that easier?

**Comment by FursinMihail** [comment]
The best source of knowledge about registers and peripherals for ST controllers is the reference manual: https://www.st.com/resource/en/reference_manual/rm0377-ultralowpower-stm32l0x1-advanced-armbased-32bit-mcus-stmicroelectronics.pdf

Take a look at the appendix A section for code examples.
Be prepared that different series of ST controllers have significant differences in working with the periphery. If you have any questions about working with CMSIS and ST microcontrollers, please contact. I can also recommend the Keil uVision environment, as for me it is very convenient (free version for non-commercial use with lemite firmware size 32kb).
